# Generated by Django 4.2.4 on 2024-06-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginIndustryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="大分類コード"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="大分類名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="大分類の説明"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OriginIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="中分類コード"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="中分類名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="中分類の説明"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industries",
                        to="corp.originindustrycategory",
                        verbose_name="大分類",
                    ),
                ),
            ],
        ),
    ]
