# Generated by Django 4.2.4 on 2024-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corp", "0003_company_origin_industry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="originindustry",
            name="code",
        ),
        migrations.RemoveField(
            model_name="originindustrycategory",
            name="code",
        ),
    ]
