# Generated by Django 4.2.4 on 2024-06-29 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corp", "0005_tagcategory_tagsubcategory_tagsmallcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_code", models.CharField(max_length=6, verbose_name="団体コード")),
                (
                    "city_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="市区町村名（漢字）"
                    ),
                ),
                (
                    "city_name_kana",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="市区町村名（カナ）"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Prefecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefecture_code",
                    models.CharField(max_length=6, verbose_name="団体コード"),
                ),
                (
                    "prefecture_name",
                    models.CharField(max_length=50, verbose_name="都道府県名（漢字）"),
                ),
                (
                    "prefecture_name_kana",
                    models.CharField(max_length=50, verbose_name="都道府県名（カナ）"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="corp.tagsmallcategory", verbose_name="タグ"
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="city",
            name="prefecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="corp.prefecture",
                verbose_name="都道府県",
            ),
        ),
    ]
