# Generated by Django 4.2.4 on 2024-06-29 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corp", "0006_city_prefecture_company_tags_delete_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="city_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="city_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="city_name_kana",
            new_name="name_kana",
        ),
        migrations.RenameField(
            model_name="prefecture",
            old_name="prefecture_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="prefecture",
            old_name="prefecture_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="prefecture",
            old_name="prefecture_name_kana",
            new_name="name_kana",
        ),
    ]
