# Generated by Django 4.2.4 on 2024-09-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corp", "0007_rename_city_code_city_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
            ],
        ),
    ]
